[server]
address = 0.0.0.0
port = 8090
shutdown_timeout_sec = 30

[onec]
base_url = http://frontmaster.keenetic.pro:17777/fm_ka/
user = testMarketplace
password = 0926Vfhrtngktqc@!
page_size = 100
timeout_ms = 10000
; Разрешить HTTP для loopback (только для локальной разработки)
allow_insecure_http = true
allow_private_network = true

[database]
conn_str = dbname=o1c_pi user=postgres password=12345678 host=localhost

[worker_pool]
threads = 2
queue_max = 100

[ozon]
client_id = 1839853
api_key = bd638f83-01e5-4b63-ae4a-fba6c3053b52
page_size = 100
timeout_ms = 60000
webhook_url = http://your-monitoring-server:9000/notify/sync-progress

[notify]
; Каждые N процентов. 1 = каждый 1%, 5 = каждые 5%, 0 = после каждой страницы
every_percent = 5
; Минимум секунд между уведомлениями
min_interval_sec = 2
