    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Обязательно доставляем meson, ninja и системный curl для воркера
          sudo apt-get install -y cmake build-essential libboost-system-dev libboost-json-dev libssl-dev libpqxx-dev pkg-config meson ninja-build libcurl4-openssl-dev

      - name: Configure CMake
        # Флаг --fresh принудительно очистит кэш самого CMake, если он подтянулся из GitHub Cache
        run: cmake -B build -S . --fresh

      - name: Build
        run: cmake --build build --config Release
